import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cvms_desktop/core/widgets/app/custom_snackbar.dart';
import 'package:cvms_desktop/features/auth/data/auth_repository.dart';
import 'package:cvms_desktop/features/violation_management/data/violation_repository.dart';
import 'package:cvms_desktop/features/violation_management/models/violation_enums.dart';
import 'package:cvms_desktop/features/violation_management/models/violation_model.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

part 'add_violation_state.dart';

class AddViolationCubit extends Cubit<AddViolationState> {
  final AuthRepository authRepository;
  final ViolationRepository _repository = ViolationRepository();

  AddViolationCubit(this.authRepository) : super(AddViolationState.initial());

  void resetForm() {
    emit(AddViolationState.initial());
  }

  void updateVehicleId(String vehicleId) {
    emit(state.copyWith(vehicleId: vehicleId));
  }

  void updateViolationType(String violationType) {
    emit(state.copyWith(violationType: violationType));
  }

  void updateReportedByUserId(String reportedByUserId) {
    emit(state.copyWith(reportedByUserId: reportedByUserId));
  }

  void updateStatus(String status) {
    emit(state.copyWith(status: status));
  }

  void clearMessage() {
    emit(state.copyWith(message: null, messageType: null));
  }

  Future<void> reportViolation({
    required String? vehicleId,
    required String violationType,
    String? reason,
  }) async {
    try {
      final currentUser = authRepository.currentUser;
      if (currentUser == null) throw Exception("User not authenticated");

      // Create a temporary ViolationEntry with empty ID (will be generated by Firestore)
      final violation = ViolationEntry(
        id: '', // Firestore will generate this
        vehicleId: vehicleId ?? '',
        reportedByUserId: currentUser.uid,
        violationType:
            reason != null ? '$violationType: $reason' : violationType,
        status: ViolationStatus.pending,
        sanctionApplied: false,
        reportedAt: Timestamp.now(),
      );

      await _repository.reportViolation(violation);
    } catch (e) {
      throw Exception('Failed to report violation: ${e.toString()}');
    }
  }

  @override
  Future<void> close() {
    return super.close();
  }
}
